[package]

name = "pcap"
version = "0.5.7"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "A packet capture API around pcap/wpcap"
keywords = ["pcap", "packet", "sniffing"]
readme = "README.md"
homepage = "https://github.com/ebfull/pcap"
repository = "https://github.com/ebfull/pcap"
documentation = "https://ebfull.github.io/pcap/"
license = "MIT OR Apache-2.0"

[dependencies]
libc = "0.2.7"

[features]
# This feature enables access to the function Capture::savefile_append.
# This is disabled by default, because it depends on a relatively recent
# version of libpcap (1.7.2).
pcap-savefile-append = []

[lib]
name = "pcap"

[[example]]
name = "listenlocalhost"
path = "examples/listenlocalhost.rs"

[[example]]
name = "getdevices"
path = "examples/getdevices.rs"

[[example]]
name = "easylisten"
path = "examples/easylisten.rs"

[[example]]
name = "savefile"
path = "examples/savefile.rs"

[[example]]
name = "getstatistics"
path = "examples/getstatistics.rs"
